DROP TABLE IF EXISTS `UNIT_HERO`;
CREATE TABLE `UNIT_HERO` (
	`unit_id` INT NOT NULL,
	`name_id` varchar(255) NOT NULL,
	PRIMARY KEY (`unit_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
