DROP TABLE IF EXISTS `UNIT_LEVEL`;
CREATE TABLE `UNIT_LEVEL` (
	`index` INT NOT NULL,
	`unit_id` INT NOT NULL,
	`level` INT NOT NULL,
	PRIMARY KEY (`index`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
